In [1]:
import numpy as np
%matplotlib notebook
import matplotlib.pyplot as plt
from scipy.integrate import odeint

# define the sytem of differential equation in python

In [2]:
def cde(var,t):
    x=var[0]
    y=var[1]
    dxdt=x*(0.1-0.0014*y)
    dydt=y*(0.08*x-0.0012)
    return [dxdt,dydt]

In [3]:
var0=[4,9]

In [4]:
cde(var0,0)

[0.3496, 2.8692]

In [5]:
t=np.arange(0,16,1)

In [6]:
t

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
solution=odeint(cde,var0,t)

In [8]:
solution

array([[4.00000000e+00, 9.00000000e+00],
       [4.35523506e+00, 1.25556492e+01],
       [4.71266240e+00, 1.80244538e+01],
       [5.05039983e+00, 2.66099708e+01],
       [5.33020265e+00, 4.02806019e+01],
       [5.48986736e+00, 6.20872547e+01],
       [5.44018379e+00, 9.61855583e+01],
       [5.08288405e+00, 1.46690649e+02],
       [4.37082895e+00, 2.14337819e+02],
       [3.38981130e+00, 2.92349225e+02],
       [2.35804074e+00, 3.67298241e+02],
       [1.49105700e+00, 4.27246344e+02],
       [8.78483164e-01, 4.68359648e+02],
       [4.94371489e-01, 4.93559453e+02],
       [2.70778297e-01, 5.07860461e+02],
       [1.46108747e-01, 5.15525645e+02]])

In [9]:
plt.plot(t,solution[:,0],'ro-')
plt.plot(t,solution[:,1],'go-')
plt.xlabel("time (Day)")
plt.ylabel("Prey and predator populaton")
plt.legend(['Prey population','predator population'])
plt.grid()
plt.show()
plt.savefig('Prey_predator_exact.png')


<IPython.core.display.Javascript object>

In [10]:
p=solution[:,0]

In [11]:
p

array([4.        , 4.35523506, 4.7126624 , 5.05039983, 5.33020265,
       5.48986736, 5.44018379, 5.08288405, 4.37082895, 3.3898113 ,
       2.35804074, 1.491057  , 0.87848316, 0.49437149, 0.2707783 ,
       0.14610875])

In [12]:
q=solution[:,1]

In [13]:
q

array([  9.        ,  12.55564925,  18.02445378,  26.60997085,
        40.28060191,  62.08725468,  96.18555834, 146.69064874,
       214.33781888, 292.34922491, 367.2982406 , 427.24634375,
       468.3596481 , 493.55945316, 507.8604614 , 515.52564514])